// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spkwyyvrgpxebxwiaqym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwa3d5eXZyZ3B4ZWJ4d2lhcXltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NjE4MzUsImV4cCI6MjA2ODEzNzgzNX0.Fv_KJrNsWzZVX4BRhL63eRI5ySmSX2RusPAvdz67PUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});